apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rc 
  labels:
    app: myapp
    type: front-end-replicaset
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-containers
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      type: front-end